# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-12 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0002_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_url', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='site_url',
        ),
        migrations.RemoveField(
            model_name='step',
            name='content',
        ),
        migrations.RemoveField(
            model_name='step',
            name='scenario',
        ),
        migrations.AddField(
            model_name='step',
            name='message',
            field=models.CharField(default='test', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='step',
            name='options',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='step',
            name='position',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='step',
            name='type',
            field=models.IntegerField(choices=[(1, b'INFO'), (2, b'YES_OR_NO'), (3, b'ACTION')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='scenario.Scenario'),
        ),
        migrations.AddField(
            model_name='step',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='scenario.Group'),
            preserve_default=False,
        ),
    ]
