# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-12 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0003_auto_20151212_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='scenario.Scenario'),
        ),
        migrations.AlterField(
            model_name='group',
            name='site_url',
            field=models.CharField(max_length=200),
        ),
    ]
