# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-12 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0004_auto_20151212_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='error_message',
            field=models.CharField(default='DEFAULT ERROR MSG: REMOVE ME', max_length=1000),
            preserve_default=False,
        ),
    ]
